# respect from https://qiita.com/hi-nakamura/items/fb841be12566e7f579f0

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - node_modules/**/*
    - config/**/*
    - Gemfile

Metrics/AbcSize:
  Max: 25
# ネストが深すぎる
Metrics/BlockNesting:
  Max: 5
# ブロックが長すぎる
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
# クラスの行数が多すぎる
Metrics/ClassLength:
  Enabled: false
# 循環的複雑度が高すぎる(ifやforなどを1メソッド内で使いすぎている)
Metrics/CyclomaticComplexity:
  Enabled: false
# メソッドの行数が多すぎる
Metrics/MethodLength:
  Enabled: false
# 引数の数が多すぎる
Metrics/ParameterLists:
  Max: 12
# 例外を抑制している
Lint/SuppressedException:
  Enabled: false
# 行が長すぎる
Layout/LineLength:
  Enabled: false
# クラスにコメントを残さない
Style/Documentation:
  Enabled: false
# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false
