version: "3.9"

services:
  app: &app_base
    build:
      context: .
      args:
        - RUBY_VERSION=2.7.2
        - NODE_VERSION=14.15.3
        - ALPINE_VERSION=3.12 # 余計なイメージのダウンロードを避けるため、ALPINEのバージョンをそろえて高速化する
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0" # 最初はコマンド引数で rails new に上書する。
    environment:
      - DATABASE_URL=mysql2://app_root:password@db:3306/app_local # database.yml を無視して接続する
      - WEBPACKER_DEV_SERVER_HOST=webpack # app コンテナから見た webpack ホストの設定
    volumes:
      - .:/app:cached # ホストへの反映の遅延を許容して高速化する
    volumes_from:
      - datastore
    ports:
      - "3000:3000"
    depends_on:
      - db

  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0 # ブラウザに対する公開ホスト名
    ports:
      - "3035:3035"
    depends_on:
      - app

  db:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=app_local
      - MYSQL_USER=app_root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306" # DBクライアント接続用にホストにも公開しておく
    volumes_from:
      - datastore

  datastore:
    image: alpine:3.12
    volumes:
      - mysql-data:/var/lib/mysql
      - vendor-bundle:/app/vendor/bundle
      - bundle:/app/.bundle
      - node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  vendor-bundle:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
